matrix:
  include:
  - language: go
    go: 1.13.x
  - language: go
    go: 1.14.x
  - language: go
    go: 1.15.x

env:
  GO111MODULE=on

install:
  - make install

script:
  - make test

before_install:
  - go get github.com/mitchellh/gox

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then make releases; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fpS3zlN0cxF7mTDOwm8K35w4NfzkwBuri6mETVyIxwl5j6+pbtcU/6tuEjgKeYLTMY/YgdpRhyj9cHnJZWZvOv+A+se+cn0/KQDZFjG2FYgb4DfmdRakxAw2VUu4iTkwNKuwd34i5gGFXZVvH8WCLeKxHtOd6xC9JfsImgieUjrrw4xRWQCtt32VtuwjOdZrny8W0wsCJ7054wTQ0MYrE0n7X7KcCpFuuizXq08GwXlLQBzPA5l2Os6i5Ih4N+Xot63p+/OZa0YpgbtdQJnDEySG5yhy+CZBP3yYPc9YVBnmRMkby+HTo1f5eEbMdaFi2ZcZl8/HOehLZOzUbJgvdAnhvAIamdX56d//rSTwlOwP/QgxvsO4ufyJdAkYsV8pI6vujQbOJ7dNLaEomOUKNYkNupiHm09aGA5Zanc6dozGmcnrZnqTOG+CikBGmhIy1Bqrm74M1PIPJKjIfTVfBY7UFznV5mRFdyp9H4WaMXmUwIyXdOxG/I+6NOFp9fWW3ajQlDlIKAxqdvH3YjlsLl0UVeA3rqPRY5FFMHPfNfZezEo+9YdhJGUyuuTE38EuD/rdfmqmmI/aNwK0rBYtkVFq/00I0WAXpt92R5Tm9ESZWeep5JxoxQruLTFi+8Jgg6vtODf7tbWatrgr16OShWwneFm5NqUzRTv4TEvlmgE=
  file_glob: true
  file: dist/**/*
  on:
    repo: MichaelMure/git-bug-migration
    go: 1.14.x
    tags: true
